"""create customer events

Revision ID: 08e9b4db12d6
Revises: 6af761d8affc
Create Date: 2026-07-29 04:34:43.023113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08e9b4db12d6'
down_revision: Union[str, Sequence[str], None] = '6af761d8affc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('product_view', 'product_search', 'add_to_cart', 'remove_from_cart', 'checkout_started', 'order_placed')", name=op.f('ck_customer_events_event_type_valid')),
    sa.CheckConstraint('user_id IS NOT NULL OR session_id IS NOT NULL', name=op.f('ck_customer_events_customer_or_session_required')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_customer_events_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_customer_events_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_customer_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_events'))
    )
    op.create_index(op.f('ix_customer_events_event_type'), 'customer_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_customer_events_occurred_at'), 'customer_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_customer_events_order_id'), 'customer_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_customer_events_product_id'), 'customer_events', ['product_id'], unique=False)
    op.create_index(op.f('ix_customer_events_session_id'), 'customer_events', ['session_id'], unique=False)
    op.create_index('ix_customer_events_session_occurred_at', 'customer_events', ['session_id', 'occurred_at'], unique=False)
    op.create_index('ix_customer_events_type_occurred_at', 'customer_events', ['event_type', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_customer_events_user_id'), 'customer_events', ['user_id'], unique=False)
    op.create_index('ix_customer_events_user_occurred_at', 'customer_events', ['user_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customer_events_user_occurred_at', table_name='customer_events')
    op.drop_index(op.f('ix_customer_events_user_id'), table_name='customer_events')
    op.drop_index('ix_customer_events_type_occurred_at', table_name='customer_events')
    op.drop_index('ix_customer_events_session_occurred_at', table_name='customer_events')
    op.drop_index(op.f('ix_customer_events_session_id'), table_name='customer_events')
    op.drop_index(op.f('ix_customer_events_product_id'), table_name='customer_events')
    op.drop_index(op.f('ix_customer_events_order_id'), table_name='customer_events')
    op.drop_index(op.f('ix_customer_events_occurred_at'), table_name='customer_events')
    op.drop_index(op.f('ix_customer_events_event_type'), table_name='customer_events')
    op.drop_table('customer_events')
    # ### end Alembic commands ###
