"""add data quality observability tables

Revision ID: 4a01e1ae11b8
Revises: 7c6225a7cf18
Create Date: 2026-08-01 19:25:16.281498

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a01e1ae11b8"
down_revision: str | Sequence[str] | None = "7c6225a7cf18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_quality_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_type", sa.String(length=50), server_default="operational", nullable=False),
        sa.Column("status", sa.String(length=20), server_default="running", nullable=False),
        sa.Column("triggered_by", sa.String(length=50), server_default="manual", nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_checks", sa.Integer(), server_default="0", nullable=False),
        sa.Column("passed_checks", sa.Integer(), server_default="0", nullable=False),
        sa.Column("warning_checks", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed_checks", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'passed', 'warning', 'failed')",
            name=op.f("ck_data_quality_runs_data_quality_run_status_valid"),
        ),
        sa.CheckConstraint(
            "passed_checks + warning_checks + failed_checks <= total_checks",
            name=op.f("ck_data_quality_runs_data_quality_run_counts_reconcile"),
        ),
        sa.CheckConstraint(
            "total_checks >= 0 AND passed_checks >= 0 AND warning_checks >= 0 AND failed_checks >= 0",
            name=op.f("ck_data_quality_runs_data_quality_run_counts_nonnegative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_quality_runs")),
    )
    op.create_index(
        op.f("ix_data_quality_runs_run_type"), "data_quality_runs", ["run_type"], unique=False
    )
    op.create_index(
        op.f("ix_data_quality_runs_started_at"), "data_quality_runs", ["started_at"], unique=False
    )
    op.create_index(
        op.f("ix_data_quality_runs_status"), "data_quality_runs", ["status"], unique=False
    )
    op.create_table(
        "data_quality_check_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("check_name", sa.String(length=160), nullable=False),
        sa.Column("check_category", sa.String(length=50), nullable=False),
        sa.Column(
            "check_source", sa.String(length=50), server_default="operational_sql", nullable=False
        ),
        sa.Column("target_name", sa.String(length=160), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("severity", sa.String(length=20), server_default="error", nullable=False),
        sa.Column(
            "observed_value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "expected_value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("failure_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IN ('info', 'warning', 'error')",
            name=op.f("ck_data_quality_check_results_data_quality_check_severity_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('passed', 'warning', 'failed')",
            name=op.f("ck_data_quality_check_results_data_quality_check_status_valid"),
        ),
        sa.CheckConstraint(
            "failure_count >= 0",
            name=op.f("ck_data_quality_check_results_data_quality_failure_count_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["data_quality_runs.id"],
            name=op.f("fk_data_quality_check_results_run_id_data_quality_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_quality_check_results")),
        sa.UniqueConstraint("run_id", "check_name", name="one_result_per_quality_run_check"),
    )
    op.create_index(
        op.f("ix_data_quality_check_results_check_category"),
        "data_quality_check_results",
        ["check_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_quality_check_results_check_source"),
        "data_quality_check_results",
        ["check_source"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_quality_check_results_run_id"),
        "data_quality_check_results",
        ["run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_quality_check_results_status"),
        "data_quality_check_results",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_quality_check_results_target_name"),
        "data_quality_check_results",
        ["target_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_data_quality_check_results_target_name"), table_name="data_quality_check_results"
    )
    op.drop_index(
        op.f("ix_data_quality_check_results_status"), table_name="data_quality_check_results"
    )
    op.drop_index(
        op.f("ix_data_quality_check_results_run_id"), table_name="data_quality_check_results"
    )
    op.drop_index(
        op.f("ix_data_quality_check_results_check_source"), table_name="data_quality_check_results"
    )
    op.drop_index(
        op.f("ix_data_quality_check_results_check_category"),
        table_name="data_quality_check_results",
    )
    op.drop_table("data_quality_check_results")
    op.drop_index(op.f("ix_data_quality_runs_status"), table_name="data_quality_runs")
    op.drop_index(op.f("ix_data_quality_runs_started_at"), table_name="data_quality_runs")
    op.drop_index(op.f("ix_data_quality_runs_run_type"), table_name="data_quality_runs")
    op.drop_table("data_quality_runs")
    # ### end Alembic commands ###
