"""add demo ingestion provenance

Revision ID: 7c6225a7cf18
Revises: cc9653d434c8
Create Date: 2026-07-30 03:56:42.610333

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c6225a7cf18"
down_revision: str | Sequence[str] | None = "cc9653d434c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_items", sa.Column("source_order_item_id", sa.String(length=80), nullable=True)
    )
    op.add_column("order_items", sa.Column("source_seller_id", sa.String(length=80), nullable=True))
    op.add_column("order_items", sa.Column("source_category", sa.String(length=160), nullable=True))
    op.add_column(
        "order_items", sa.Column("unit_cost", sa.Numeric(precision=12, scale=2), nullable=True)
    )
    op.add_column(
        "order_items",
        sa.Column(
            "discount_amount", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "order_items",
        sa.Column(
            "tax_amount", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False
        ),
    )
    op.create_index(
        op.f("ix_order_items_source_order_item_id"),
        "order_items",
        ["source_order_item_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_order_items_source_seller_id"),
        "order_items",
        ["source_seller_id"],
        unique=False,
    )

    op.create_check_constraint(
        op.f("ck_order_items_discount_amount_nonnegative"),
        "order_items",
        "discount_amount >= 0",
    )
    op.create_check_constraint(
        op.f("ck_order_items_tax_amount_nonnegative"),
        "order_items",
        "tax_amount >= 0",
    )

    op.drop_constraint(
        op.f("ck_order_items_line_total_matches_quantity"),
        "order_items",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_order_items_line_total_matches_quantity"),
        "order_items",
        ("line_total = unit_price * quantity - discount_amount + tax_amount"),
    )
    op.add_column("orders", sa.Column("source_order_id", sa.String(length=80), nullable=True))
    op.add_column("orders", sa.Column("source_region", sa.String(length=30), nullable=True))
    op.add_column("orders", sa.Column("order_channel", sa.String(length=40), nullable=True))
    op.add_column("orders", sa.Column("device_type", sa.String(length=40), nullable=True))
    op.add_column(
        "orders",
        sa.Column(
            "discount_amount", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "orders",
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.create_index(
        op.f("ix_orders_source_order_id"),
        "orders",
        ["source_order_id"],
        unique=True,
    )

    op.create_check_constraint(
        op.f("ck_orders_discount_amount_nonnegative"),
        "orders",
        "discount_amount >= 0",
    )

    op.drop_constraint(
        op.f("ck_orders_total_matches_components"),
        "orders",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_orders_total_matches_components"),
        "orders",
        ("total_amount = subtotal - discount_amount + shipping_amount + tax_amount"),
    )
    op.add_column("products", sa.Column("source_product_id", sa.String(length=80), nullable=True))
    op.add_column("products", sa.Column("sku", sa.String(length=100), nullable=True))
    op.add_column("products", sa.Column("seller_source_id", sa.String(length=80), nullable=True))
    op.add_column("products", sa.Column("subcategory", sa.String(length=160), nullable=True))
    op.add_column("products", sa.Column("cost", sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column(
        "products", sa.Column("weight_kg", sa.Numeric(precision=10, scale=3), nullable=True)
    )
    op.add_column(
        "products", sa.Column("review_count", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "products", sa.Column("return_rate", sa.Numeric(precision=8, scale=6), nullable=True)
    )
    op.add_column("products", sa.Column("launch_date", sa.Date(), nullable=True))
    op.add_column(
        "products",
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.create_index(
        op.f("ix_products_seller_source_id"), "products", ["seller_source_id"], unique=False
    )
    op.create_index(op.f("ix_products_sku"), "products", ["sku"], unique=True)
    op.create_index(
        op.f("ix_products_source_product_id"),
        "products",
        ["source_product_id"],
        unique=True,
    )

    op.create_check_constraint(
        op.f("ck_products_cost_nonnegative"),
        "products",
        "cost IS NULL OR cost >= 0",
    )
    op.create_check_constraint(
        op.f("ck_products_review_count_nonnegative"),
        "products",
        "review_count >= 0",
    )
    op.create_check_constraint(
        op.f("ck_products_return_rate_valid"),
        "products",
        ("return_rate IS NULL OR (return_rate >= 0 AND return_rate <= 1)"),
    )
    op.add_column("users", sa.Column("source_customer_id", sa.String(length=80), nullable=True))
    op.add_column("users", sa.Column("region", sa.String(length=30), nullable=True))
    op.add_column("users", sa.Column("country_code", sa.String(length=2), nullable=True))
    op.add_column("users", sa.Column("segment", sa.String(length=50), nullable=True))
    op.add_column("users", sa.Column("signup_channel", sa.String(length=50), nullable=True))
    op.add_column("users", sa.Column("account_status", sa.String(length=30), nullable=True))
    op.add_column(
        "users", sa.Column("is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.create_index(
        op.f("ix_users_source_customer_id"), "users", ["source_customer_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_source_customer_id"), table_name="users")
    op.drop_column("users", "is_demo")
    op.drop_column("users", "account_status")
    op.drop_column("users", "signup_channel")
    op.drop_column("users", "segment")
    op.drop_column("users", "country_code")
    op.drop_column("users", "region")
    op.drop_column("users", "source_customer_id")
    op.drop_index(op.f("ix_products_source_product_id"), table_name="products")
    op.drop_index(op.f("ix_products_sku"), table_name="products")
    op.drop_index(op.f("ix_products_seller_source_id"), table_name="products")
    op.drop_constraint(
        op.f("ck_products_return_rate_valid"),
        "products",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_products_review_count_nonnegative"),
        "products",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_products_cost_nonnegative"),
        "products",
        type_="check",
    )

    op.drop_column("products", "is_demo")
    op.drop_column("products", "launch_date")
    op.drop_column("products", "return_rate")
    op.drop_column("products", "review_count")
    op.drop_column("products", "weight_kg")
    op.drop_column("products", "cost")
    op.drop_column("products", "subcategory")
    op.drop_column("products", "seller_source_id")
    op.drop_column("products", "sku")
    op.drop_column("products", "source_product_id")
    op.drop_index(op.f("ix_orders_source_order_id"), table_name="orders")
    op.drop_constraint(
        op.f("ck_orders_total_matches_components"),
        "orders",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_orders_total_matches_components"),
        "orders",
        "total_amount = subtotal + shipping_amount + tax_amount",
    )

    op.drop_constraint(
        op.f("ck_orders_discount_amount_nonnegative"),
        "orders",
        type_="check",
    )

    op.drop_column("orders", "is_demo")
    op.drop_column("orders", "discount_amount")
    op.drop_column("orders", "device_type")
    op.drop_column("orders", "order_channel")
    op.drop_column("orders", "source_region")
    op.drop_column("orders", "source_order_id")
    op.drop_index(op.f("ix_order_items_source_seller_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_source_order_item_id"), table_name="order_items")
    op.drop_constraint(
        op.f("ck_order_items_line_total_matches_quantity"),
        "order_items",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_order_items_line_total_matches_quantity"),
        "order_items",
        "line_total = unit_price * quantity",
    )

    op.drop_constraint(
        op.f("ck_order_items_tax_amount_nonnegative"),
        "order_items",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_order_items_discount_amount_nonnegative"),
        "order_items",
        type_="check",
    )

    op.drop_column("order_items", "tax_amount")
    op.drop_column("order_items", "discount_amount")
    op.drop_column("order_items", "unit_cost")
    op.drop_column("order_items", "source_category")
    op.drop_column("order_items", "source_seller_id")
    op.drop_column("order_items", "source_order_item_id")
    # ### end Alembic commands ###
