"""create customer churn scores

Revision ID: cc9653d434c8
Revises: 08e9b4db12d6
Create Date: 2026-07-29 06:10:22.802193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9653d434c8'
down_revision: Union[str, Sequence[str], None] = '08e9b4db12d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_churn_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('feature_snapshot_date', sa.Date(), nullable=False),
    sa.Column('days_since_last_order', sa.Integer(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('orders_last_30d', sa.Integer(), nullable=False),
    sa.Column('orders_last_90d', sa.Integer(), nullable=False),
    sa.Column('lifetime_spend', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('average_order_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('spend_last_90d', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('account_age_days', sa.Integer(), nullable=False),
    sa.Column('is_single_order_customer', sa.Boolean(), nullable=False),
    sa.Column('churn_probability', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('predicted_churn_flag', sa.Boolean(), nullable=False),
    sa.Column('risk_rank', sa.Integer(), nullable=False),
    sa.Column('risk_percentile', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('risk_decile', sa.Integer(), nullable=False),
    sa.Column('risk_segment', sa.String(length=30), nullable=False),
    sa.Column('recommended_action', sa.String(length=80), nullable=False),
    sa.Column('scoring_population_size', sa.Integer(), nullable=False),
    sa.Column('probability_threshold', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('scored_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_segment IN ('high_risk', 'medium_risk', 'low_risk')", name=op.f('ck_customer_churn_scores_risk_segment_valid')),
    sa.CheckConstraint('churn_probability >= 0 AND churn_probability <= 1', name=op.f('ck_customer_churn_scores_churn_probability_valid')),
    sa.CheckConstraint('days_since_last_order >= 0', name=op.f('ck_customer_churn_scores_days_since_last_order_nonnegative')),
    sa.CheckConstraint('lifetime_spend >= 0', name=op.f('ck_customer_churn_scores_lifetime_spend_nonnegative')),
    sa.CheckConstraint('probability_threshold >= 0 AND probability_threshold <= 1', name=op.f('ck_customer_churn_scores_probability_threshold_valid')),
    sa.CheckConstraint('risk_decile BETWEEN 1 AND 10', name=op.f('ck_customer_churn_scores_risk_decile_valid')),
    sa.CheckConstraint('total_orders >= 1', name=op.f('ck_customer_churn_scores_eligible_customer_has_order')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_customer_churn_scores_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_churn_scores')),
    sa.UniqueConstraint('user_id', 'feature_snapshot_date', 'model_version', name='one_score_per_user_snapshot_model')
    )
    op.create_index(op.f('ix_customer_churn_scores_feature_snapshot_date'), 'customer_churn_scores', ['feature_snapshot_date'], unique=False)
    op.create_index(op.f('ix_customer_churn_scores_model_version'), 'customer_churn_scores', ['model_version'], unique=False)
    op.create_index(op.f('ix_customer_churn_scores_risk_segment'), 'customer_churn_scores', ['risk_segment'], unique=False)
    op.create_index(op.f('ix_customer_churn_scores_user_id'), 'customer_churn_scores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_churn_scores_user_id'), table_name='customer_churn_scores')
    op.drop_index(op.f('ix_customer_churn_scores_risk_segment'), table_name='customer_churn_scores')
    op.drop_index(op.f('ix_customer_churn_scores_model_version'), table_name='customer_churn_scores')
    op.drop_index(op.f('ix_customer_churn_scores_feature_snapshot_date'), table_name='customer_churn_scores')
    op.drop_table('customer_churn_scores')
    # ### end Alembic commands ###
